git:
  depth: 5

jobs:
  include:
    - stage: "Build and Test Java"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
    - stage: "Build and Test Nodejs"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
      after_script:
        - docker login -u "$User" -p "$PSWD"

        - docker push frontend frontend:latest

        - docker push backend
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"