git:
  depth: 5

jobs:
  include:
    - stage: "Build and Test Java"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
      script:
        - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar-Dsonar.projectKey=Theo-tech_sample-application-students
      after_script:
        - docker build -t "$User"/backend .
        - docker login -u "$User" -p "$PSWD"
        - docker push "$User"/backend
    - stage: "Build and Test Nodejs"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
      after_script:
        - docker build -t "$User"/frontend .
        - docker login -u "$User" -p "$PSWD"
        - docker push "$User"/frontend
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"

addons:
    sonarcloud:
      organization: "Theo-tech"
      token: 
        secure: $SONAR_TOKEN